
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create global tables
Parameters:
  PrimaryKeyName:
    Description: HashType PrimaryKey Name
    Default: Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  PrimaryKeyType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: '[S|N]'
    MinLength: '1'
    MaxLength: '1'
    ConstraintDescription: must be either S or N
  EnvironmentName:
    Description: Defines enviroment name
    Type: String
    Default: Staging
  Region:
    Description: Defines region name
    Type: String
    Default: Staging

Mappings: 
  ThroughputMap: 
    Staging: 
      "ReadCapacityUnits": "2",
      "MinWriteCapacity": "2",
      "MaxWriteCapacity": "5",
      "SeedWriteCapacity": "3"
    Perf: 
      "ReadCapacityUnits": "6",
      "MinWriteCapacity": "3",
      "MaxWriteCapacity": "6",
      "SeedWriteCapacity": "4"
    E2E: 
      "ReadCapacityUnits": "7",
      "MinWriteCapacity": "4",
      "MaxWriteCapacity": "7",
      "SeedWriteCapacity": "5"
    Production: 
      "ReadCapacityUnits": "8",
      "MinWriteCapacity": "5",
      "MaxWriteCapacity": "8",
      "SeedWriteCapacity": "6"

Resources:
 GlobalTableTest:
     Type: 'AWS::DynamoDB::GlobalTable'
     Properties:
         TableName: !Join [ "-", [ !Ref 'EnvironmentName', mytable1 ] ]
         AttributeDefinitions:
         - AttributeName: !Ref 'PrimaryKeyName'
           AttributeType: !Ref 'PrimaryKeyType'
         KeySchema:
         - AttributeName: !Ref 'PrimaryKeyName'
           KeyType: HASH
         BillingMode: PROVISIONED
         StreamSpecification:
             StreamViewType: NEW_IMAGE
         TimeToLiveSpecification:
            #AttributeName:  !Ref 'PrimaryKeyName'
            Enabled: False
         SSESpecification:
             #KMSMasterKeyId: arn:aws:kms:us-west-2:996302627310:key/196e26da-a5f6-43f5-9b3c-3f84a60f97a9
             SSEEnabled: True
             SSEType: KMS

         
         WriteProvisionedThroughputSettings:
           WriteCapacityAutoScalingSettings:
              MinCapacity : !FindInMap [ThroughputMap, !Ref "EnvironmentName", MinWriteCapacity]
              MaxCapacity : !FindInMap [ThroughputMap, !Ref "EnvironmentName", MaxWriteCapacity]
              SeedCapacity : !FindInMap [ThroughputMap, !Ref "EnvironmentName", SeedWriteCapacity]
              TargetTrackingScalingPolicyConfiguration:
                       DisableScaleIn: False
                       ScaleInCooldown: 60
                       ScaleOutCooldown: 60
                       TargetValue: 70
         Replicas:
         - Region: !Ref 'Region'
           PointInTimeRecoverySpecification:
             PointInTimeRecoveryEnabled: True
           Tags:
             - Key: Name
               Value: mytable1
             - Key: Region
               Value: east
             - Key: Env
               Value: !Ref 'EnvironmentName'
           ReadProvisionedThroughputSettings: 
               ReadCapacityUnits: !FindInMap [ThroughputMap, !Ref "EnvironmentName", ReadCapacityUnits]
           
#          - Region: us-west-1
#            PointInTimeRecoverySpecification:
#                PointInTimeRecoveryEnabled: false
#            Tags:
#             - Key: Name
#               Value: mytable1
#             - Key: Region
#               Value: west 
#             - Key: Env
#               Value: !Ref 'EnvironmentName'
#            ReadProvisionedThroughputSettings:
#                ReadCapacityUnits: 4
#            ReadProvisionedThroughputSettings:
#                   MaxCapacity: 4
#                   MinCapacity: 10
#                   SeedCapacity: 5
#                   TargetTrackingScalingPolicyConfiguration: 
#                              DisableScaleIn: False
#                              ScaleInCooldown: 60
#                              ScaleOutCooldown: 60
#                              TargetValue: 70


